name: Daily Esports Slack Update

on:
  schedule:
    - cron: "7 0 * * *"
  workflow_dispatch:

jobs:
  send-slack-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send Slack message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
        run: python src/main.py
